### ISSUE TITLE
[feature request] The DeletionProtection mechanism reject Namespace deletion when PVCs are included under NS

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1223]
**What would you like to be added**:
When there is active Pods in this namespace, openkruise can reject Namespace Deletion, details: https://openkruise.io/docs/user-manuals/deletionprotection .

But pvc is also a very important resource, so if pvc exists under Namespace, NS is also not allowed to delete.
Related Code: https://github.com/openkruise/kruise/blob/master/pkg/webhook/util/deletionprotection/deletion_protection.go#L52

**Comment by kevin1689-cloud** [comment]
@zmberg 
Hi, I have a solution to this issue:

I added a logic to the ValidateNamespaceDeletion function: for the namespce which labeled with policy.kruise.io/delete-protection=Cascading, determine whether there is existing pvc under the namespace. If so, delete the namespace is prohibited.

The code I added is shown below:
```
		pvc := v1.PersistentVolumeClaimList{}
		if err := c.List(context.TODO(), &pvc, client.InNamespace(namespace.Name)); err != nil {
			return fmt.Errorf("forbidden by ResourcesProtectionDeletion for list pvc error: %v", err)
		}
		var pvcCount int
		for range pvc.Items {
			pvcCount++
		}
		if pvcCount > 0 {
			return fmt.Errorf("forbidden by ResourcesProtectionDeletion for %s=%s and existing pvc %d>0", policyv1alpha1.DeletionProtectionKey, val, pvcCount)
		}
```
The final ValidateNamespaceDeletion function is as shown below:
```
func ValidateNamespaceDeletion(c client.Client, namespace *v1.Namespace) error {
	if !utilfeature.DefaultFeatureGate.Enabled(features.ResourcesDeletionProtection) || namespace.DeletionTimestamp != nil {
		return nil
	}
	switch val := namespace.Labels[policyv1alpha1.DeletionProtectionKey]; val {
	case policyv1alpha1.DeletionProtectionTypeAlways:
		return fmt.Errorf("forbidden by ResourcesProtectionDeletion for %s=%s", policyv1alpha1.DeletionProtectionKey, val)
	case policyv1alpha1.DeletionProtectionTypeCascading:
		pods := v1.PodList{}
		if err := c.List(context.TODO(), &pods, client.InNamespace(namespace.Name)); err != nil {
			return fmt.Errorf("forbidden by ResourcesProtectionDeletion for list pods error: %v", err)
		}
		var activeCount int
		for i := range pods.Items {
			pod := &pods.Items[i]
			if kubecontroller.IsPodActive(pod) {
				activeCount++
			}
		}
		if activeCount > 0 {
			return fmt.Errorf("forbidden by ResourcesProtectionDeletion for %s=%s and active pods %d>0", policyv1alpha1.DeletionProtectionKey, val, activeCount)
		}

		pvc := v1.PersistentVolumeClaimList{}
		if err := c.List(context.TODO(), &pvc, client.InNamespace(namespace.Name)); err != nil {
			return fmt.Errorf("forbidden by ResourcesProtectionDeletion for list pvc error: %v", err)
		}
		var pvcCount int
		for range pvc.Items {
			pvcCount++
		}
		if pvcCount > 0 {
			return fmt.Errorf("forbidden by ResourcesProtectionDeletion for %s=%s and existing pvc %d>0", policyv1alpha1.DeletionProtectionKey, val, pvcCount)
		}
	default:
	}
	return nil
}
```
I tested my code and the result meet expectations:
1. Create a namespce "protection" and label it
![image](https://user-images.githubusercontent.com/69347704/226110135-9e3b3863-f8ca-42a5-9d6f-f4e21685e615.png)
2. Create a pvc in that namespace
![image](https://user-images.githubusercontent.com/69347704/226110211-0b9665ab-f78d-4ee7-9bd5-96dc789e5b38.png)
3. Try to delete the namespce, the namespace can't be deleted and show an error to tell user the reason is there are existing pvc in the namespce
![image](https://user-images.githubusercontent.com/69347704/226110393-ca65e46d-67d9-4548-a96f-bba1362e459d.png)

please kindly review my solution and tell me if there's any question. If this solution is ok,  I would be happy to submit a pull request and resolve the issue.
