### ISSUE TITLE
kruise daemon failed to detect runtime

### ISSUE THREAD

**Issue by 1569099266** [openkruise/kruise#1319]
Failed to new daemon: failed to new runtime factory: not found container runtime sock
![9f54a4e2bd4239b2662f26327b5b543](https://github.com/openkruise/kruise/assets/46311200/8c175578-1592-4405-84c6-64b79be0e7d1)
![image](https://github.com/openkruise/kruise/assets/46311200/0d5fad9e-978e-4a65-8bff-d0c0649e37c2)
![image](https://github.com/openkruise/kruise/assets/46311200/69dedc81-4d47-40e7-b949-bc7ed3f2836c)
![image](https://github.com/openkruise/kruise/assets/46311200/82b74286-40d4-4c9f-8918-5e0983aa3f9d)

**Comment by furykerry** [comment]
@1569099266 please make sure your container runtime. If it is indeed docker and your installation of docker does not contain dockershim, we can check if it is possible to relax the detection rule. Currently openkruise require both docker.sock and dockershim.sock. 

In addition, dockershim support is removed in k8s 1.24, so i think you should migrate to containerd or other CRI compatible runtime, otherwise even basic k8s function e.g. pod creation will not works
