### ISSUE TITLE
[feature request] 类似于 job + cronjob + daemonset 这样的 CRD 控制器

### ISSUE THREAD

**Issue by kong62** [openkruise/kruise#215]
**What would you like to be added**:
实现过类似于 job + cronjob + daemonset 这样的 CRD 控制器，功能需求大致是这样的：
1. 添加新节点的时候，自动在新节点上启动一次 job，完成后退出                      【不满足】
2. 当有修改节点的任务 job 分配的时候，启动一次 job，完成后退出                  【满足】
3. 每天定时在所有节点上启动一次 job，完成后退出                                            【不满足】

**Why is this needed**:
代替 ansible 这样的工具做节点上的批量修改，速度比他们快。而且很少占用资源。另外主要就是针对新加入集群的节点自动处理，这一般人为去做比较慢。

**Comment by Ghostbaby** [comment]
类似初始化系统，但是不是所有主机都加入k8s集群

**Comment by kong62** [comment]
其实主要就是2个作用把：
1. 类似于创建云主机时候的初始化脚本，用于一次性初始化新创建的节点
2. 类似于代替 ansible 这样的工具，专门用于日常做一些任务，比如定时删除镜像，删除停止的容器，拷贝文件等等

**Comment by FillZpp** [comment]
> 添加新节点的时候，自动在新节点上启动一次 job，完成后退出 【不满足】

`BroadcastJob` can do this with `spec.completionPolicy.type: "Never"`, it guarantees a completed job on all desired Nodes.
When new nodes are added, the pods will be triggered automatically on those new nodes.

> 当有修改节点的任务 job 分配的时候，启动一次 job，完成后退出 【满足】

`BroadcastJob` can do this.

> 每天定时在所有节点上启动一次 job，完成后退出 【不满足】

A cron `BroadcastJob` is in our plan.

**Comment by rishi-anand** [comment]
@FillZpp, @Fei-Guo, If `BroadcastCronJob` is in the plan and if no one is working on it then I would like to implement it.

**Comment by Fei-Guo** [comment]
> @FillZpp, @Fei-Guo, If `BroadcastCronJob` is in the plan and if no one is working on it then I would like to implement it.

Hi, Rishi, 

You are very welcome to contribute for this feature. From high level perspective, this can be done by either simply enhancing upstream CronJob to support BroadcastJob spec in addition to JobSpec or adding Cron capability directly in BroadcastJob.

I personally feel the formal is a cleaner solution but I understand the downside of introducing one more CRD.  If we do the latter, the controller logic is complicated since we need to handle `ConcurrencyPolicy` specifically. 

Can you write a proposal maximally following the template in /docs/proposals/YYYYMMDD-template.md?   After reviewing the design proposal, we can go from there.

**Comment by rishi-anand** [comment]
Yes @Fei-Guo, I feel having BroadcastCronJob just like k8s cron job would be better solution. I have generated all boilerplate codes for BroadcastCronJob resource and controller. I will create a PR for initial review.

Yes, I will create proposal docs.

**Comment by rishi-anand** [comment]
Added proposal https://github.com/openkruise/kruise/pull/427

**Comment by FillZpp** [comment]
@kong62 It has been implemented in AdvancedCronJob.

**Comment by kong62** [comment]
@FillZpp 666
