### ISSUE TITLE
[BUG] partition not in expected state

### ISSUE THREAD

**Issue by shiyan2016** [openkruise/kruise#261]
**What happened**:
Create a cloneset with replicas 8, maxSurge 10% and maxUnavaliable 10%, update the cloneset and set partition 5, after that will be 4 updated pods and 5 old pods. Then update partition to 7, it still 4 updated pods and 5 old pods. And if I delete one updated pod, it will create a old pod.

**What you expected to happen**:
When update partition to 7, should keep 2 updated pods and 7 old pods.

**Environment**:
- Kruise version: master
- Kubernetes version (use `kubectl version`): 1.14.6

**Comment by FillZpp** [comment]
@shiyan2016 This is by design, not a bug.

CloneSet can only update Pods to the latest revision which matches its template, but it cloud not update Pods to a historic template.

It's just like the original StatefulSet. If you update `partition` from 5 to 7, controller will do nothing unless you delete the Pods with order 5 or 6.

**Comment by shiyan2016** [comment]
ok, I will close this issue.

**Comment by mkloveyy** [comment]
@FillZpp Will CloneSet enable to reset partition to a bigger value (such as 5 -> 7) in future? Perhaps for rollback deploy or something else. Thx!
