### ISSUE TITLE
[feature request] Can we add currentRevision state in CloneSet status?

### ISSUE THREAD

**Issue by shiyan2016** [openkruise/kruise#270]
**What would you like to be added**:
Add currentRevision in CloneSet status.

**Why is this needed**:
Like StatefulSet, it's status has CurrentRevision and UpdateRevision.Which is more clearly for looking pods on current revision and update revision.

**Comment by FillZpp** [comment]
@shiyan2016 The truth is, `UpdateRevision` is the latest revision, but `CurrentRevision` may not be the revision for all non-updated Pods, this is why we didn't put it into status.

For example, a CloneSet with `replicas=10`, the original revision is `v1`. First you set `partition=5` and update to revision `v2`, then you set `partition=8` and update to revision `v3`. At this moment, all Pods might stay 5 * v1, 3 * v2, 2 * v3 (also there are other conditions).

We can tell you the UpdateRevision is `v3`, but we couldn't say CurrentRevision is `v1` or `v2`, because there are multiple old revisions.

**Comment by shiyan2016** [comment]
@FillZpp I did not consider that. Thank you for your answer. I will close it.
