### ISSUE TITLE
[QUESTION] cloneset pod name

### ISSUE THREAD

**Issue by tudou34** [openkruise/kruise#540]
ReplicaSet use metadata.GenerateName to generate unique pod name
but Cloneset use getOrGenAvailableIDs function to generate unique pod name.
Why cloneset design like this？

**Comment by FillZpp** [comment]
@tudou34 It is because CloneSet supports `volumeClaimTemplate`, which creates PVCs before Pods and they all have the random ID such as `xp52p`.

So kruise have to generate the ID locally. And both kube-apiserver and kruise generate the ID using `k8s.io/apimachinery/pkg/util/rand` package.

Ref: https://github.com/kubernetes/apiserver/blob/master/pkg/storage/names/generate.go#L49

**Comment by tudou34** [comment]
thanks
