### ISSUE TITLE
[feature request] let CI do more check

### ISSUE THREAD

**Issue by daixiang0** [openkruise/kruise#662]
**What would you like to be added**:

Add golangci-lint as Github Action. I have done at local, if possible, I will post it.

**Why is this needed**:

I have seen some PRs related to format, while there is no lint check in CI. Enable lint check would import code quality and make project better.

**Comment by FillZpp** [comment]
@daixiang0 Thanks. We do have golangci-lint in the actions: https://github.com/openkruise/kruise/blob/master/.github/workflows/ci.yaml#L51

Do you have any suggestions for any lint plugin else should we enable?

**Comment by daixiang0** [comment]
I think it is better to add config in repo rather than use flags to override default, which become easy to maintain rather than switch to golangci-lint repo to see default config and merge them in mind.

**Comment by daixiang0** [comment]
Also no lint run as https://github.com/openkruise/kruise/pull/653

**Comment by FillZpp** [comment]
> Also no lint run as #653

It is because first-time contributors need a maintainer to approve running workflows. 😄 
![image](https://user-images.githubusercontent.com/7541475/124855759-06834f00-dfdc-11eb-9c66-c0c53a9c7ef8.png)

> I think it is better to add config in repo rather than use flags to override default

Do you mean define a `.golangci.yml` config file in repo instead of writing the flags in `ci.yaml`? It's ok for me, are you willing to assign it?

**Comment by daixiang0** [comment]
Got it, happy to do that.
