### ISSUE TITLE
[BUG]Advanced-DaemonSet Rollback available?

### ISSUE THREAD

**Issue by zhanbinHo** [openkruise/kruise#869]
Does advance-daemonset support rollback?

**Comment by hantmac** [comment]
Of course, Advanced-DaemonSet also has RevisionHistory to allow rollback like native DaemonSet.

**Comment by zhanbinHo** [comment]
How do I list the RevisionHistory of Advance-Daemonset?

**Comment by zhanbinHo** [comment]
If it's native,I can do it like that
![image](https://user-images.githubusercontent.com/20354178/147635397-542ee1fa-620c-4173-b761-307e54c62afd.png)

**Comment by hantmac** [comment]
You can use kruise api to get the RevisionHistory of Advance-Daemonset, and native kubectl can't do this now because the `rollout`  commands in original `kubectl` can only work for built-in workloads, such as Deployment and StatefulSet. So we have a [kubectl plugin](https://github.com/openkruise/kruise-tools) ,but this plugin only support CloneSet, asts rollout cmd now. It's nice if you can open an issue about advanced daemonset rollout cmd or make a pr.
