### ISSUE TITLE
[BUG] failed calling webhook "msidecarset.kb.io"

### ISSUE THREAD

**Issue by LetLifeStop** [openkruise/kruise#908]
**What happened**:
I follow the (tutorial)[https://openkruise.io/docs/user-manuals/sidecarset/#create-sidecarset] to apply sidecartset.yaml, this error occured. 
```
Error from server (InternalError): error when creating "sidecarset.yaml": Internal error occurred: failed calling webhook "msidecarset.kb.io": Post "https://kruise-webhook-service.kruise-system.svc:443/mutate-apps-kruise-io-v1alpha1-sidecarset?timeout=30s": Address is not allowed
``` 
I  already install this [https://openkruise.io/docs/installation#install-with-helm] successfully
**What you expected to happen**:
apply sidecarset.yaml success
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`): aws eks version: 1.20
- Install details (e.g. helm install args):
- Others:

**Comment by FillZpp** [comment]
Hi @LetLifeStop , it is because when using a custom CNI (such as Weave or Calico) on EKS, the webhook cannot be reached. You can see [this](https://stackoverflow.com/questions/57292517/istio-failed-calling-admission-webhook-address-is-not-allowed).

Maybe you could solve it by setting `--set manager.hostNetwork=true` to let the webhook use host network. (You have to `helm upgrade kruise` again with this flag)

Please tell us if you succeed with the additional flag, we will add this tip on our installation doc. Thanks.

**Comment by LetLifeStop** [comment]
this really worked! Thanks.
